---
apiVersion: v2
type: application
name: external-dns-watcher
description: Watch any resource and generate External DNS records
version: 1.2.0
appVersion: 1.2.0
home: https://github.com/kubehippie/external-dns-watcher
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/hetzner.svg
keywords:
  - external-dns
  - watcher
  - cluster-api
maintainers:
  - email: thomas@webhippie.de
    name: tboerger
    url: https://github.com/tboerger
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/changes: |+
    ## [1.2.0](https://github.com/kubehippie/external-dns-watcher/compare/v1.1.3...v1.2.0) (2025-11-24)


    ### Features

    * **minor:** update module sigs.k8s.io/external-dns to v0.20.0 ([#44](https://github.com/kubehippie/external-dns-watcher/issues/44)) ([3d09e83](https://github.com/kubehippie/external-dns-watcher/commit/3d09e83d6cd762b055ae17697e2a1fa3fdb25f41))


    ### Bugfixes

    * **deps:** update golang:1.25 docker digest to 6981837 ([#52](https://github.com/kubehippie/external-dns-watcher/issues/52)) ([c046579](https://github.com/kubehippie/external-dns-watcher/commit/c046579751339babc6c0b97e987d98d9e959d7cd))
    * **deps:** update golang:1.25 docker digest to f60eaa8 ([#47](https://github.com/kubehippie/external-dns-watcher/issues/47)) ([971ddd1](https://github.com/kubehippie/external-dns-watcher/commit/971ddd1804e8cdca61496d481ebc9ada0ae14d5b))

...
