---
apiVersion: v2
type: application
name: external-dns-watcher
description: Watch any resource and generate External DNS records
version: 1.1.1
appVersion: 1.1.1
home: https://github.com/kubehippie/external-dns-watcher
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/hetzner.svg
keywords:
  - external-dns
  - watcher
  - cluster-api
maintainers:
  - email: thomas@webhippie.de
    name: tboerger
    url: https://github.com/tboerger
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/changes: |+
    ## [1.1.1](https://github.com/kubehippie/external-dns-watcher/compare/v1.1.0...v1.1.1) (2025-11-03)


    ### Bugfixes

    * **patch:** update module github.com/onsi/ginkgo/v2 to v2.27.2 ([#30](https://github.com/kubehippie/external-dns-watcher/issues/30)) ([29896e1](https://github.com/kubehippie/external-dns-watcher/commit/29896e19414ddc1e8ebbddbc362b37e2f933c57f))

...
